# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/user_window.ui'
#
# Created: Sun Jul 12 22:26:54 2009
#      by: PyQt4 UI code generator 4.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_UserWindow(object):
    def setupUi(self, UserWindow):
        UserWindow.setObjectName("UserWindow")
        UserWindow.resize(508, 570)
        self.verticalLayout_5 = QtGui.QVBoxLayout(UserWindow)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter = QtGui.QSplitter(UserWindow)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtGui.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.blipArea = QtGui.QScrollArea(self.groupBox)
        self.blipArea.setMinimumSize(QtCore.QSize(0, 180))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 223, 222, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 223, 222, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 223, 222, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 223, 222, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.blipArea.setPalette(palette)
        self.blipArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.blipArea.setFrameShadow(QtGui.QFrame.Plain)
        self.blipArea.setLineWidth(0)
        self.blipArea.setWidgetResizable(True)
        self.blipArea.setObjectName("blipArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.blipArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 482, 180))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rootBlip = OpTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rootBlip.sizePolicy().hasHeightForWidth())
        self.rootBlip.setSizePolicy(sizePolicy)
        self.rootBlip.setMinimumSize(QtCore.QSize(0, 160))
        self.rootBlip.setMaximumSize(QtCore.QSize(16777215, 160))
        self.rootBlip.setObjectName("rootBlip")
        self.verticalLayout.addWidget(self.rootBlip)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.blipArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.blipArea)
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblVersion = QtGui.QLabel(self.widget)
        self.lblVersion.setObjectName("lblVersion")
        self.horizontalLayout.addWidget(self.lblVersion)
        spacerItem1 = QtGui.QSpacerItem(486, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cmdReply = QtGui.QPushButton(self.widget)
        self.cmdReply.setObjectName("cmdReply")
        self.horizontalLayout.addWidget(self.cmdReply)
        self.verticalLayout_2.addWidget(self.widget)
        self.groupBox_3 = QtGui.QGroupBox(self.splitter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tblPending = QtGui.QTableView(self.groupBox_3)
        self.tblPending.setObjectName("tblPending")
        self.verticalLayout_4.addWidget(self.tblPending)
        self.groupBox_2 = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tblCached = QtGui.QTableView(self.groupBox_2)
        self.tblCached.setObjectName("tblCached")
        self.verticalLayout_3.addWidget(self.tblCached)
        self.verticalLayout_5.addWidget(self.splitter)

        self.retranslateUi(UserWindow)
        QtCore.QMetaObject.connectSlotsByName(UserWindow)

    def retranslateUi(self, UserWindow):
        UserWindow.setWindowTitle(QtGui.QApplication.translate("UserWindow", "User \"NoName\"", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("UserWindow", "Blips", None, QtGui.QApplication.UnicodeUTF8))
        self.lblVersion.setText(QtGui.QApplication.translate("UserWindow", "v0", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdReply.setText(QtGui.QApplication.translate("UserWindow", "Reply", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("UserWindow", "Pending Operations", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("UserWindow", "Cached Operations", None, QtGui.QApplication.UnicodeUTF8))

from op_text_edit import OpTextEdit
