#!/bin/bash

#
# PyGoWave Server - The Python Google Wave Server
# Copyright 2009-2010 Patrick Schneider <patrick.p2k.schneider@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Get program's home directory
SCRIPT_PATH=`readlink -f $0`
SCRIPT_DIR=`dirname $SCRIPT_PATH`
PYGORPC_HOME=`readlink -f "${SCRIPT_DIR}/.."`

NODENAME=erlang
LOG_BASE=/var/log/pygowave
SERVER_START_ARGS=""

# Source in configuration
[ -f /etc/pygowave-erlang-rpc.conf ] && . /etc/pygowave-erlang-rpc.conf

# Set defaults where not overridden
[ "${PYGORPC_NODENAME}" == "" ] && PYGORPC_NODENAME=${NODENAME}
[ "${PYGORPC_START_ARGS}" == "" ] && PYGORPC_START_ARGS=${SERVER_START_ARGS}
[ "${PYGORPC_LOG_BASE}" == "" ] && PYGORPC_LOG_BASE=${LOG_BASE}
[ "${PYGORPC_LOGS}" == "" ] && PYGORPC_LOGS=${LOG_FILE}
[ "${PYGORPC_LOGS}" == "" ] && PYGORPC_LOGS=${PYGORPC_LOG_BASE}/pygowave-${PYGORPC_NODENAME}-rpc.log
[ "${PYGORPC_BOOT_FILE}" == "" ] && PYGORPC_BOOT_FILE=pygowave_rpc

PYGORPC_EBIN_ROOT="${PYGORPC_HOME}/ebin"
PYGORPC_BOOT_FILE="${PYGORPC_EBIN_ROOT}/pygowave_rpc"

exec erl \
	-sname "${PYGORPC_NODENAME}" \
	-boot "${PYGORPC_BOOT_FILE}" \
	-kernel error_logger '{file,"'${PYGORPC_LOGS}'"}' \
	${PYGORPC_START_ARGS} \
	"$@"
